export const mockSession = {
  data: {
    authenticated: true,
    locale: 'en_GB',
    currentProvider: {
      uuid: 'b1a8b05e-3542-4037-bbd3-998ee9c4057z',
      display: 'Test User',
      person: {
        uuid: 'ddd5fa89-48a6-432e-abb8-0d11b4be7e4f',
        display: 'Test User',
      },
      identifier: 'UNKNOWN',
      attributes: [],
    },
    sessionLocation: {
      uuid: 'b1a8b05e-3542-4037-bbd3-998ee9c40574',
      display: 'Test Location',
      name: 'Test Location',
      description: null,
      address1: null,
      address2: null,
      cityVillage: null,
      stateProvince: null,
      country: null,
      postalCode: null,
      latitude: null,
      longitude: null,
      countyDistrict: null,
      address3: null,
      address4: null,
      address5: null,
      address6: null,
      tags: [],
      parentLocation: null,
      childLocations: [],
      retired: false,
      attributes: [],
      address7: null,
      address8: null,
      address9: null,
      address10: null,
      address11: null,
      address12: null,
      address13: null,
      address14: null,
      address15: null,
    },
    user: {
      uuid: 'ddd5fa89-48a6-432e-abb8-0d11b4be7e4f',
      display: 'admin',
      username: 'admin',
      systemId: 'admin',
      userProperties: {},
      person: {
        uuid: 'ddd5fa89-48a6-432e-abb8-0d11b4be7e4f',
        display: 'Test User',
      },
      privileges: [],
      roles: [
        {
          uuid: '8d94f852-c2cc-11de-8d13-0010c6dffd0f',
          display: 'System Developer',
          links: [],
        },
      ],
      retired: false,
      locale: 'en_GB',
      allowedLocales: ['en_GB', 'es'],
    },
    sessionId: 'D4F7D4D4-6A6D-4D4D-8D4D-4D4D4D4D4D4D',
  },
};
